version: '3.7'
services:
  mongodb:
    image: mongo:4.4.6
    restart: always
    container_name: mongodb_db_graphql
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongodb
volumes:
  mongodb_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongodb-volume/db
